name: Djinni test workflow

on:
  push:
    branches: ["cicd-playground"]
  # workflow_dispatch:
  #   inputs:
  #     jobtype:
  #       description: "Select job type"
  #       required: true
  #       type: choice
  #       options: 
  #         - "fetch"
  #         - "apply"
  #     role:
  #       description: "Specify role"
  #       type: string
  #       required: true
  #       default: 'python'

jobs:
  octoffers-setup:
    runs-on: ubnutu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: octoffers/.github/workflows/setup.yml

